name: Python application
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Validate JSON
        uses: 'docker://nhalstead00/validate-json-action:latest'
        env:
          INPUT_SCHEMA: /src/resources/schema.json
          INPUT_JSONS: /json/*
        - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          python -m pip install -U pytest
          pytest
